Upgrade to github.com/aws/aws-sdk-go-v2/service/kms v1.18.4
The reason i'm doing this update is because we seem to be hitting
https://github.com/aws/aws-sdk-go-v2/issues/1253 occasionally in production.  We'll see errors like
this from `shush`:

> ERROR: operation error KMS: Decrypt, failed to sign request: failed to retrieve credentials:
> failed to decode buildkite-agent-non-production-arm-Role EC2 IMDS role credentials, context
> canceled

It appears that this is a known issue (https://github.com/aws/aws-sdk-go-v2/issues/1253) which has
been addressed (https://github.com/aws/aws-sdk-go-v2/pull/1448) as of 7/Oct/2021, but shush still
uses github.com/aws/aws-sdk-go-v2/service/kms
v1.1.2 (https://github.com/aws/aws-sdk-go-v2/tree/service/kms/v1.1.2 released 13/Mar/2021) which
doesn't include this fix.

Let's include the latest kms package, v1.18.4 which was released 12/Aug/2022
(https://github.com/aws/aws-sdk-go-v2/tree/service/kms/v1.18.4).